const BOOTSTRAP_APP_ARGUMENT = "Ym9vdHN0cmFw"
const BURN_APP_ARGUMENT = "YnVybg=="
const MINT_APP_ARGUMENT = "bWludA=="
const REDEEM_APP_ARGUMENT = "cmVkZWVt"
const SWAP_APP_ARGUMENT = "c3dhcA=="

const TESTNET_VALIDATOR_APP_ID_V1_0 = 21580889
const TESTNET_VALIDATOR_APP_ID_V1_1 = 62368684

const MAINNET_VALIDATOR_APP_ID_V1_0 = 350338509
const MAINNET_VALIDATOR_APP_ID_V1_1 = 552635992

const TESTNET_VALIDATOR_APP_ID = TESTNET_VALIDATOR_APP_ID_V1_1
const MAINNET_VALIDATOR_APP_ID = MAINNET_VALIDATOR_APP_ID_V1_1

export {BOOTSTRAP_APP_ARGUMENT,BURN_APP_ARGUMENT,MINT_APP_ARGUMENT,REDEEM_APP_ARGUMENT,SWAP_APP_ARGUMENT,TESTNET_VALIDATOR_APP_ID,MAINNET_VALIDATOR_APP_ID}